<a href="https://colab.research.google.com/github/Yashvir835/Pytorch-Fire/blob/main/01_pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

# Creating tensors

#### 1.)Scaler
A scalar is a single number and in tensor it is a zero dimension tensor

In [14]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [15]:
scalar.ndim,scalar.dtype

(0, torch.int64)

In [16]:
scalar.item(),scalar.item

(9, <function Tensor.item>)

#### 1.)Vector
A vector is a single dimension tensor but can contain many numbers where the scalar can have one number.

In [17]:
vector = torch.tensor([4,7])
vector

tensor([4, 7])

In [18]:
vector.ndim

1

##### 🔥Fun fact :
To tell the number of dimensions a tesnor in pytorch have count the number of square brackets on the outside (```[```) but only need to count one side.

In [20]:
vector.shape

torch.Size([2])

#### 3.)Matrix


In [19]:
MATRIX = torch.tensor(
    [
      [4,7],
      [9,2]
    ]
    )
MATRIX

tensor([[4, 7],
        [9, 2]])

In [20]:
MATRIX.ndim,MATRIX.dtype

(2, torch.int64)

In [43]:
MATRIX.shape

torch.Size([2, 2])

In [47]:
TENSOR = torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6],
            [6,7,8]
        ]
    ]
)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [48]:
TENSOR.shape

torch.Size([1, 3, 3])

In [49]:
TENSOR.ndim

3

#### Creating the random tensors

In [8]:
random_tensor = torch.rand(size=(3,4))

In [9]:
random_tensor

tensor([[0.9884, 0.7398, 0.6169, 0.7544],
        [0.9847, 0.6965, 0.5946, 0.9078],
        [0.6747, 0.2281, 0.5681, 0.5378]])

In [17]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim,random_image_size_tensor.dtype

(torch.Size([224, 224, 3]), 3, torch.float32)

In [15]:
random_image_size_tensor

tensor([[[0.7594, 0.6174, 0.3569],
         [0.0123, 0.4950, 0.0312],
         [0.4067, 0.0173, 0.8949],
         ...,
         [0.9029, 0.3679, 0.6159],
         [0.7967, 0.9022, 0.0103],
         [0.6769, 0.2737, 0.6295]],

        [[0.7993, 0.2852, 0.1313],
         [0.7213, 0.3528, 0.8984],
         [0.6161, 0.4267, 0.8725],
         ...,
         [0.6081, 0.0098, 0.6337],
         [0.9803, 0.1445, 0.4210],
         [0.8894, 0.3196, 0.0905]],

        [[0.7850, 0.5485, 0.5333],
         [0.4547, 0.4232, 0.3566],
         [0.6004, 0.6083, 0.0675],
         ...,
         [0.6143, 0.4998, 0.7838],
         [0.0801, 0.0301, 0.8901],
         [0.5502, 0.6188, 0.8940]],

        ...,

        [[0.9487, 0.5349, 0.3127],
         [0.0962, 0.4665, 0.1544],
         [0.6775, 0.5435, 0.8200],
         ...,
         [0.4935, 0.5842, 0.4938],
         [0.2277, 0.6402, 0.9789],
         [0.4924, 0.0102, 0.5498]],

        [[0.2151, 0.4580, 0.5419],
         [0.6899, 0.4172, 0.9950],
         [0.

In [16]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [24]:
# creating a tesnor of all ones
ones = torch.ones(size=(3,4))
ones,ones.dtype,ones.dim(),ones.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [29]:
zero_to_ten = torch.arange(0,10,1)

In [30]:
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
# copying the shape of the a tensor
ten_zeros =  torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [43]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device='cpu',
                               requires_grad=False)

In [44]:
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

 #### Most common issues in the deeplearning:
 1.) Device Mismatch


 2.) Shape Mismatch


 3.) datatype Mismatch

In [45]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16