<a href="https://colab.research.google.com/github/Yashvir835/Pytorch-Fire/blob/main/01_pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.9.0+cpu'

# Creating tensors

#### 1.)Scaler
A scalar is a single number and in tensor it is a zero dimension tensor

In [2]:
scalar = torch.tensor(9)
scalar

tensor(9)

In [3]:
scalar.ndim,scalar.dtype

(0, torch.int64)

In [4]:
scalar.item(),scalar.item

(9, <function Tensor.item>)

#### 1.)Vector
A vector is a single dimension tensor but can contain many numbers where the scalar can have one number.

In [5]:
vector = torch.tensor([4,7])
vector

tensor([4, 7])

In [6]:
vector.ndim

1

##### 🔥Fun fact :
To tell the number of dimensions a tesnor in pytorch have count the number of square brackets on the outside (```[```) but only need to count one side.

In [7]:
vector.shape

torch.Size([2])

#### 3.)Matrix


In [8]:
MATRIX = torch.tensor(
    [
      [4,7],
      [9,2]
    ]
    )
MATRIX

tensor([[4, 7],
        [9, 2]])

In [9]:
MATRIX.ndim,MATRIX.dtype

(2, torch.int64)

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6],
            [6,7,8]
        ]
    ]
)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR.ndim

3

#### Creating the random tensors

In [14]:
random_tensor = torch.rand(size=(3,4))

In [15]:
random_tensor

tensor([[0.5801, 0.7660, 0.3460, 0.2500],
        [0.3389, 0.5180, 0.4587, 0.7586],
        [0.9979, 0.7332, 0.2941, 0.5733]])

In [16]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim,random_image_size_tensor.dtype

(torch.Size([224, 224, 3]), 3, torch.float32)

In [17]:
random_image_size_tensor

tensor([[[0.4750, 0.9018, 0.5067],
         [0.4379, 0.4395, 0.7726],
         [0.4431, 0.5433, 0.6307],
         ...,
         [0.6473, 0.2004, 0.3208],
         [0.4940, 0.9107, 0.8538],
         [0.6671, 0.6425, 0.0683]],

        [[0.7911, 0.5665, 0.1130],
         [0.9008, 0.7586, 0.2196],
         [0.2459, 0.0641, 0.7479],
         ...,
         [0.8079, 0.2111, 0.4378],
         [0.1877, 0.7744, 0.8978],
         [0.3183, 0.6703, 0.3188]],

        [[0.2930, 0.5448, 0.9274],
         [0.4230, 0.8177, 0.2668],
         [0.1345, 0.8153, 0.1353],
         ...,
         [0.6018, 0.7436, 0.3169],
         [0.7687, 0.7558, 0.5842],
         [0.3096, 0.8180, 0.2698]],

        ...,

        [[0.6937, 0.7761, 0.5428],
         [0.7243, 0.3128, 0.4827],
         [0.8012, 0.3212, 0.6921],
         ...,
         [0.7588, 0.4309, 0.6311],
         [0.6705, 0.9967, 0.7668],
         [0.7427, 0.6291, 0.4101]],

        [[0.1464, 0.7418, 0.8763],
         [0.3375, 0.3379, 0.1319],
         [0.

In [18]:
# creating a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros,zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
# creating a tesnor of all ones
ones = torch.ones(size=(3,4))
ones,ones.dtype,ones.dim(),ones.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [20]:
zero_to_ten = torch.arange(0,10,1)

In [21]:
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# copying the shape of the a tensor
ten_zeros =  torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
ten_ones = torch.ones_like(input=zero_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device='cpu',
                               requires_grad=False)

In [25]:
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

 #### Most common issues in the deeplearning:
 1.) Device Mismatch


 2.) Shape Mismatch


 3.) datatype Mismatch

In [26]:
float_16_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

#### Manipulating tensors (tensor operations)

1.)  Addition

In [32]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

2.) Multiply

In [33]:
tensor*10

tensor([10, 20, 30])

🔥 Fun fact  :
Tensor values doesn't change unless reassigned

3.)  Subtraction

In [34]:
# subtract and reassign
tensor = tensor-10
tensor

tensor([-9, -8, -7])

In [35]:
# add and reassign

tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [38]:
torch.mul(tensor,10),torch.multiply(tensor,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [39]:
tensor

tensor([1, 2, 3])

In [40]:
# Element wise multiplication , each mulitplies itself with its equivalent index 0->0,1->1,2->2
print(tensor,"*",tensor)
print("Equals : ",tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals :  tensor([1, 4, 9])


4.) Matrix Multiplication

Rule:

1.) The inner dimensions must  match:

```(3,2) @ (3,2)``` won't work

```(2,2) @ (2,3)``` will work

2.) The resulting matrix has the shape of the outer dimension

```(2,3) @ (3,2) ``` -> ```(2,2)```



```Important point to remember ```

Last two dimensions are always treated as matrices.

All dimensions before the last two are batch dimensions.

1D × 1D → dot product → scalar output.

2D × 2D → normal matrix multiplication.

2D × 1D → matrix–vector multiplication.

1D × 2D → vector–matrix multiplication.

If any tensor has ≥3 dimensions, batched matrix multiplication is used.

Matrix multiplication requires inner dimensions to match.

Batch dimensions must be broadcastable.

Batch dimensions are compared from right to left.

Two batch dimensions are compatible if they are equal or one is 1.

Broadcasting reuses data; it does not copy it.

Output batch shape is the broadcasted batch shape.

Output matrix shape is (n × p).

1D tensors are temporarily expanded and then squeezed back.

Dot-product (1D × 1D) does not support out=.

matmul automatically chooses the correct multiplication type.

In [69]:
# vector x vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
print(torch.matmul(tensor1, tensor2).size())
# matrix x vector
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
print(torch.matmul(tensor1, tensor2).size())
# batched matrix x broadcasted vector
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
print(torch.matmul(tensor1, tensor2).size())
# batched matrix x batched matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
print(torch.matmul(tensor1, tensor2).size())
# batched matrix x broadcasted matrix
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
print(torch.matmul(tensor1, tensor2).size())


torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


In [70]:
torch.matmul(tensor,tensor)

tensor(14)

In [71]:
tensor @ tensor

tensor(14)

In [72]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 481 µs, sys: 952 µs, total: 1.43 ms
Wall time: 1.27 ms


tensor(14)

In [77]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 675 µs, total: 675 µs
Wall time: 563 µs


tensor(14)

In [78]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [79]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [80]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [81]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [82]:
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [91]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=8) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,  0.6104],
        [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,  1.0926],
        [ 6.7696,  3.1736, -0.2486,  0.9506, -0.3216,  3.7842,  2.8995,  1.5748]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 8])


#### Finding the min, max, mean, sum, etc (aggregation,go from more values to less values))

In [92]:
x =torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [109]:
print(f"min : {x.min()}")
print(f"max : {x.max()}")
print(f"mean : {x.type(torch.float64).mean()}")
print(f"sum : {x.sum()}")

min : 0
max : 90
mean : 45.0
sum : 450


In [110]:
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [112]:
print(f"index of min value : {x.argmin()}")
print(f"index of max vale : {x.argmax()}")

index of min value : 0
index of max vale : 9


In [114]:
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [116]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [117]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

#### Reshaping, stacking, squeezing and unsqueezing

In [133]:
x = torch.arange(1.,9.)
x , x.shape , x.ndim, x

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]),
 torch.Size([8]),
 1,
 tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

If we use reshape and manipulate the new tensor and previous tensor , both will remain independent (creates deep copy of the original data variable)

In [134]:
x_reshaped = x.reshape(1,2,4)
x_reshaped,x_reshaped.shape,x_reshaped.ndim,x_reshaped

(tensor([[[1., 2., 3., 4.],
          [5., 6., 7., 8.]]]),
 torch.Size([1, 2, 4]),
 3,
 tensor([[[1., 2., 3., 4.],
          [5., 6., 7., 8.]]]))

But in  the view it creates the new view of the same tensor(creates shallow copy of original data variable)

In [135]:
z = x.view(1,8)
z, z.shape,z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]), 2)

In [136]:
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8.]))

In [137]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.]])

In [142]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.]])

In [143]:
x_squeezed = x_reshaped.squeeze()
x_squeezed,x_squeezed.shape

(tensor([[5., 2., 3., 4.],
         [5., 6., 7., 8.]]),
 torch.Size([2, 4]))

In [144]:
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed,x_unsqueezed.shape


(tensor([[[5., 2., 3., 4.],
          [5., 6., 7., 8.]]]),
 torch.Size([1, 2, 4]))

In [146]:
x_unsqueezed = x_squeezed.unsqueeze(dim=2)
x_unsqueezed,x_unsqueezed.shape

(tensor([[[5.],
          [2.],
          [3.],
          [4.]],
 
         [[5.],
          [6.],
          [7.],
          [8.]]]),
 torch.Size([2, 4, 1]))

🔥 Fun Face :

Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original

In [151]:
x_original = torch.rand(size=(224,224,3))
print(x_original,x_original.shape)
x_permuted = x_original.permute(2,0,1)
print("_______-----")
print(x_permuted.shape,x_permuted)

tensor([[[0.8884, 0.4063, 0.9704],
         [0.0090, 0.9739, 0.6662],
         [0.5070, 0.1831, 0.5304],
         ...,
         [0.9180, 0.1074, 0.4719],
         [0.4635, 0.4980, 0.3307],
         [0.9469, 0.0963, 0.1071]],

        [[0.1039, 0.4384, 0.5516],
         [0.7077, 0.3997, 0.8505],
         [0.4260, 0.6252, 0.1089],
         ...,
         [0.9970, 0.6220, 0.7662],
         [0.4659, 0.2153, 0.2009],
         [0.8007, 0.8076, 0.1035]],

        [[0.7639, 0.0719, 0.9183],
         [0.0487, 0.5940, 0.5141],
         [0.1997, 0.7445, 0.1934],
         ...,
         [0.3536, 0.5528, 0.6080],
         [0.4917, 0.0167, 0.6949],
         [0.2952, 0.2941, 0.6813]],

        ...,

        [[0.8045, 0.6356, 0.1594],
         [0.0767, 0.6900, 0.8978],
         [0.9789, 0.9457, 0.5751],
         ...,
         [0.2390, 0.8644, 0.4469],
         [0.0090, 0.9487, 0.3141],
         [0.4585, 0.2544, 0.8727]],

        [[0.8314, 0.1558, 0.2839],
         [0.2056, 0.6660, 0.0822],
         [0.

Indexing

In [152]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [153]:
print(f"First square bracket : \n{x[0]}")
print(f"Second square bracket : \n{x[0][0]}")
print(f"Third square bracket : \n{x[0][0][0]}")
#

First square bracket : 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket : 
tensor([1, 2, 3])
Third square bracket : 
1


In [154]:
x[:,0]

tensor([[1, 2, 3]])

In [155]:
x[:,:,1]

tensor([[2, 5, 8]])

In [157]:
x[:,1,1]

tensor([5])

In [158]:
x[0,0,:]

tensor([1, 2, 3])